config/routes.rb
Rails.application.routes.draw do
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= article.title %>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Article", new_article_path, class: "new_article"%>

app/views/articles/show.html.erb
<h1> <%= @article.title %></h1>

<p> <%= @article.body %></p>

<%= link_to "<< Back to Articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>